    <!--FEEDBACK SECTION--> 
    <section>
        <div class="container">
            <p>Feedback Message :-<?php echo $this->name; ?></p>
            <div class="form-group">
                    <textarea name="message" id="message" required="required" class="form-control" rows="3" placeholder="Message"></textarea>
            </div>
            <button type="submit" class="btn btn-success">Submit FEEDBACK</button>
        </div>
    </section>
    <!--END FEEDBACK SECTION-->