    <!-- NAV SECTION -->
    <div class="navbar navbar-inverse navbar-fixed-top">
       
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->basePath(); ?>/">YOUR LOGO</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="<?php echo $this->basePath(); ?>/">HOME</a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/package">PACKAGE</a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/gallery">GALLERY</a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/mission">MISSION</a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/contact">CONTACT</a></li>
<!--                    <form class="navbar-form navbar-right">
                        <div class="form-group">
                            <input type="email" placeholder="Email" class="form-control" required>
                        </div>
                        <div class="form-group">
                          <input type="password" placeholder="Password" class="form-control" required>
                        </div>
                        <button type="submit" class="btn btn-success">Sign in</button>
                    </form>-->
                </ul>
            </div>
           
        </div>
    </div>
    <!--END NAV SECTION -->