<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <meta property='og:locale' content='en_IN'/>
	<meta property='og:type' content='home'/>
	<meta property='og:title' content='Find a Tracker Application ABC.com'/>
	<meta property='og:description' content='Find somebody with common friends or interest at ABC.com'/>
	<meta property='og:url' content='http://www.abc.com'/>
	<meta property='og:site_name' content='abc.com'/>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>
        
        <?php $this->headLink()->appendStylesheet($this->basePath('assets/prettyPhoto/css/prettyPhoto.css')) ?>
        <?php $this->headLink()->appendStylesheet($this->basePath('/assets/css/font-awesome.min.css')) ?>
        <?php $this->headLink()->appendStylesheet($this->basePath('/assets/css/font-awesome-animation.css')) ?>
        <?php $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ?>
        
        <?php $this->headScript()->appendFile($this->basePath("assets/prettyPhoto/js/jquery.prettyPhoto.js")); ?>
        <?php $this->headScript()->appendFile($this->basePath("js/custom.js")); ?>

    </head>
    <body>
        <?php echo $this->partial('layout/header', array('vr' => 'zf2')); ?>
	<?php echo $this->partial('layout/promobar', array('vr' => 'zf2')); ?>

        <div class="container"  >
            <?php echo $this->content; ?>
        </div>
        
        <?php echo $this->partial('layout/footer', array('company' => 'Zend Technologies Ltd')); ?>
        <!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
