<?php echo $this->doctype(); ?>

<html lang="en">
    <head>      
        <?php echo $this->headMeta()
            ->setCharset('utf-8')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ?>
        
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <meta property='og:locale' content='en_IN'/>
	<meta property='og:type' content='home'/>
	<meta property='og:title' content='Find a Tracker Application ABC.com'/>
	<meta property='og:description' content='Find somebody with common friends or interest at ABC.com'/>
	<meta property='og:url' content='http://www.abc.com'/>
	<meta property='og:site_name' content='abc.com'/>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->appendStylesheet($this->basePath('css/bootstrap.min.css'))
            ->appendStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->appendStylesheet($this->basePath('css/style.css'))
            //Assets Styles
            ->appendStylesheet($this->basePath('assets/core/css/core.css'))
            ->appendStylesheet($this->basePath('assets/core/css/font-awesome.min.css'))
            ->appendStylesheet($this->basePath('assets/core/css/font-awesome-animation.css'))
            ->appendStylesheet($this->basePath('assets/prettyPhoto/css/prettyPhoto.css'))
        ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath('js/jquery.min.js'))
            ->appendFile($this->basePath('js/bootstrap.min.js'))
            //Assets Scripts
            ->appendFile($this->basePath('assets/prettyPhoto/js/jquery.prettyPhoto.js'))
            ->appendFile($this->basePath('assets/core/js/custom.js'))
        ?>

    </head>
    <body>
        <?php echo $this->partial('layout/header', array('vr' => 'zf2')); ?>
	<?php echo $this->partial('layout/promobar', array('vr' => 'zf2')); ?>

            <?php echo $this->content; ?>
        
        <?php echo $this->partial('layout/footer', array('company' => 'Zend Technologies Ltd')); ?>
        <!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
