    <!-- PROMOBAR SECTION -->
<?php
/*
 * Author : Hasib Khan
 * created: 24 july 2014
 */
//flags
$IsPromoEnable = 0; // 0 to disable Promobar
if($IsPromoEnable){?>
    <section id="header_info" style="text-align: center">
    <div class="alert alert-info" role="alert">
        <a href="#" onclick="_gaq.push(['_trackEvent', 'InfoBar', 'Default-InviteFriends', 'promo-bar']); return false;">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span> personality You and Your Friends Deserve to meet some once special, Invite them to get more awesome matches faster in 2014!</span>
        </a>
        <button type="button" class="btn btn-xs btn-primary" onclick="jQuery(this).parent('div').remove();">Dismiss</button>
    </div>
    <div class="alert alert-info" role="alert">
        <a href="#" onclick="_gaq.push(['_trackEvent', 'InfoBar', 'Default-InviteFriends', 'promo-bar']); return false;">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span> personality You and Your Friends Deserve to meet some once special, Invite them to get more awesome matches faster in 2014!</span>
        </a>
        <button type="button" class="btn btn-xs btn-primary" onclick="jQuery(this).parent('div').remove();">Dismiss</button>
    </div>
    </section>
<?php }?>
    
    <!--END PROMOBAR SECTION -->