    <!--CONTACT SECTION-->    
    <section  id="services-sec">
        <div class="container">
            <div class="row ">
                <div class="text-center g-pad-bottom">
                   <div class="col-md-4 col-sm-4 alert-info">
                            <h4><i class="fa fa-laptop fa-2x" ></i>&nbsp;Our Location </h4>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            </p>
                            
                    </div>
                    <div class="col-md-4 col-sm-4 alert-success">
                            <h4><i class="fa fa-microphone fa-2x" ></i>&nbsp;Our Values</h4>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            </p>
                            
                    </div>
                   
                    <div class="col-md-4 col-sm-4 alert-danger">
                            <h4><i class="fa fa-pencil fa-2x" ></i>&nbsp; Our Mission </h4>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            </p>
                          
                    </div>
                </div>
                  </div>
            
        
        </div>
    </section>
    
    <section>
        <div class="container">
             
            <div class="row g-pad-bottom">
                <div class="col-md-6 ">
                    <h2>Lorem ipsum dolor sit amet</h2>
                 
                    <p>
                         <strong> Address: </strong> &nbsp;Newyork City, Your Country, Pin-000000.  
                        <br />
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                           Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.              
                    </p>
                    <form>
                        <div class="row">
                            <div class="col-md-6 ">
                                <div class="form-group">
                                    <input type="text" class="form-control" required="required" placeholder="Name">
                                </div>
                            </div>
                            <div class="col-md-6 ">
                                <div class="form-group">
                                    <input type="text" class="form-control" required="required" placeholder="Email address">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 ">
                                <div class="form-group">
                                    <textarea name="message" id="message" required="required" class="form-control" rows="3" placeholder="Message"></textarea>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success">Submit Request</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-6">
                   <iframe class="cnt" src="https://www.google.com/maps/embed/v1/place?q=Raebareli%2C%20Uttar%20Pradesh%2C%20India&key=AIzaSyCWVHJXncc_mYxqxW8Nto0RrjpwS4wd0wQ"></iframe>

                </div>
            </div>
        </div>
    </section>
    <!--END CONTACT SECTION-->