<?php 
$this->headTitle($this->page_title);

?>
    <!-- PORTFOLIO SECTION-->
   <section id="port-sec">
       <div class="container">
            <div class="row g-pad-bottom">
                <div class="text-center g-pad-bottom">
                   <div class="col-md-12 col-sm-12 alert-info">
                            <h4><i class="fa fa-desktop fa-2x" ></i>&nbsp;See Destination Gallery</h4>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            </p>
                            
                    </div>
                   
                   
                   
                </div>
                  </div>
           <div class="row g-pad-bottom" >
                               <div class="col-md-10 col-md-offset-1 col-sm-12" >
                    <ul class="portfolio-items col-3">
                        <li class="portfolio-item">
                            <div class="item-main">
                                <div class="portfolio-image">
                                    <img src="<?php echo $this->basePath(); ?>/assets/img/portfolio/thumb/t1.png" alt="">
                                    <div class="overlay">
                                        <a class="preview btn btn-danger" title="Image Title Here" href="<?php echo $this->basePath(); ?>/assets/img/portfolio/big/b1.png"><i class=" fa fa-eye"></i></a>
                                    </div>
                                </div>
                                <h5>Lorem ipsum dolor sit amet</h5>
                            </div>
                        </li>
                       
                        <li class="portfolio-item">
                            <div class="item-main">
                                <div class="portfolio-image">
                                    <img src="<?php echo $this->basePath(); ?>/assets/img/portfolio/thumb/t2.png" alt="">
                                    <div class="overlay">
                                        <a class="preview btn btn-danger" title="Image Title Here" href="<?php echo $this->basePath(); ?>/assets/img/portfolio/big/b2.png"><i class=" fa fa-eye"></i></a>
                                    </div>
                                </div>
                                <h5>Lorem ipsum dolor sit amet</h5>
                            </div>
                        </li>
                        <li class="portfolio-item">
                            <div class="item-main">
                                <div class="portfolio-image">
                                    <img src="<?php echo $this->basePath(); ?>/assets/img/portfolio/thumb/t3.png" alt="">
                                    <div class="overlay">
                                        <a class="preview btn btn-danger" title="Image Title Here" href="<?php echo $this->basePath(); ?>/assets/img/portfolio/big/b3.png"><i class=" fa fa-eye"></i></a>
                                    </div>
                                </div>
                                <h5>Lorem ipsum dolor sit amet</h5>
                            </div>
                        </li>
                        <li class="portfolio-item">
                            <div class="item-main">
                                <div class="portfolio-image">
                                    <img src="<?php echo $this->basePath(); ?>/assets/img/portfolio/thumb/t4.png" alt="">
                                    <div class="overlay">
                                        <a class="preview btn btn-danger" title="Image Title Here" href="<?php echo $this->basePath(); ?>/assets/img/portfolio/big/b4.png"><i class=" fa fa-eye"></i></a>
                                    </div>
                                </div>
                                <h5>Lorem ipsum dolor sit amet</h5>
                            </div>
                        </li>
                        <li class="portfolio-item">
                            <div class="item-main">
                                <div class="portfolio-image">
                                    <img src="<?php echo $this->basePath(); ?>/assets/img/portfolio/thumb/t5.png" alt="">
                                    <div class="overlay">
                                        <a class="preview btn btn-danger" title="Image Title Here" href="<?php echo $this->basePath(); ?>/assets/img/portfolio/big/b5.png"><i class=" fa fa-eye"></i></a>
                                    </div>
                                </div>
                                <h5>Lorem ipsum dolor sit amet</h5>
                            </div>
                        </li>
                        <li class="portfolio-item ">
                            <div class="item-main">
                                <div class="portfolio-image">
                                    <img src="<?php echo $this->basePath(); ?>/assets/img/portfolio/thumb/t6.png" alt="">
                                    <div class="overlay">
                                        <a class="preview btn btn-danger" title="Image Title Here" href="<?php echo $this->basePath(); ?>/assets/img/portfolio/big/b6.png"><i class=" fa fa-eye"></i></a>
                                    </div>
                                </div>
                                <h5>Lorem ipsum dolor sit amet</h5>
                            </div>
                        </li>
                        <li class="portfolio-item ">
                           <div class="item-main">
                                <div class="portfolio-image">
                                    <img src="<?php echo $this->basePath(); ?>/assets/img/portfolio/thumb/t7.png" alt="">
                                    <div class="overlay">
                                        <a class="preview btn btn-danger" title="Image Title Here" href="<?php echo $this->basePath(); ?>/assets/img/portfolio/big/b7.png"><i class=" fa fa-eye"></i></a>
                                    </div>
                                </div>
                                <h5>Lorem ipsum dolor sit amet</h5>
                            </div>
                        </li>
                        <li class="portfolio-item ">
                           <div class="item-main">
                                <div class="portfolio-image">
                                    <img src="<?php echo $this->basePath(); ?>/assets/img/portfolio/thumb/t8.png" alt="">
                                    <div class="overlay">
                                        <a class="preview btn btn-danger" title="Image Title Here" href="<?php echo $this->basePath(); ?>/assets/img/portfolio/big/b8.png"><i class=" fa fa-eye"></i></a>
                                    </div>
                                </div>
                                <h5>Lorem ipsum dolor sit amet</h5>
                            </div>
                        </li>
                         <li class="portfolio-item">
                            <div class="item-main">
                                <div class="portfolio-image">
                                    <img src="<?php echo $this->basePath(); ?>/assets/img/portfolio/thumb/t9.png" alt="">
                                    <div class="overlay">
                                        <a class="preview btn btn-danger" title="Image Title Here" href="<?php echo $this->basePath(); ?>/assets/img/portfolio/big/b9.png"><i class=" fa fa-eye"></i></a>
                                    </div>
                                </div>
                                <h5>Lorem ipsum dolor sit amet</h5>
                            </div>
                        </li>
                    </ul>
                </div>
           </div>
       </div>
   </section>
     <!-- END PORTFOLIO SECTION-->
    
         <?php echo $this->partial('/application/index/mission'); //this will call view of mission action ?>   
     
    <?php echo $this->partial('partials/feedback.phtml', array("name"=>"hasib"));?>