    <!--Package SECTION-->    
    <section  id="services-sec">
        <div class="container">
            <div class="row ">
                <div class="text-center g-pad-bottom">
                   <div class="col-md-4 col-sm-4 alert-info">
                            <h4><i class="fa fa-laptop fa-2x" ></i>&nbsp;Free To Use </h4>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            </p>
                            
                    </div>
                    <div class="col-md-4 col-sm-4 alert-success">
                            <h4><i class="fa fa-microphone fa-2x" ></i>&nbsp;100%  Responsive </h4>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                                 Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            </p>
                            
                    </div>
                   
                    <div class="col-md-4 col-sm-4 alert-danger">
                            <h4><i class="fa fa-pencil fa-2x" ></i>&nbsp; Customizable </h4>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            </p>
                          
                    </div>
                </div>
            </div>
            <div class="row go-marg">

                <div class="col-md-4 col-sm-4">
                      <div class="panel panel-default">

                    <div class="panel-body">
                         <h4 class="adjst">Tour Package One #1 </h4>
                        <p>
                               Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                     Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                            </p>

                         <span class="label label-danger">Cost: 100 $</span>
                    </div>
                </div> 

                </div>
               <div class="col-md-4 col-sm-4">
                      <div class="panel panel-default">

                    <div class="panel-body">
                         <h4 class="adjst">Tour Package Two #2 </h4>
                        <p>
                               Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                     Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                            </p>
                          <span class="label label-danger">Cost: 500 $</span>

                    </div>
                </div> 

                </div>
                 <div class="col-md-4 col-sm-4">
                      <div class="panel panel-default">

                    <div class="panel-body">
                         <h4 class="adjst">Tour Package Three #3 </h4>
                        <p>
                               Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                     Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                            </p>

                         <span class="label label-danger">Cost: 300 $</span>
                    </div>
                </div> 

                </div>
            </div>
            <div class="row go-marg">

                <div class="col-md-4 col-sm-4">
                      <div class="panel panel-default">

                    <div class="panel-body">
                         <h4 class="adjst">Tour Package Four #4 </h4>
                        <p>
                               Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                     Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                            </p>

                         <span class="label label-danger">Cost: 200 $</span>
                    </div>
                </div> 

                </div>
               <div class="col-md-4 col-sm-4">
                      <div class="panel panel-default">

                    <div class="panel-body">
                         <h4 class="adjst">Tour Package Five #5 </h4>
                        <p>
                               Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                     Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                            </p>

                         <span class="label label-danger">Cost: 300 $</span>
                    </div>
                </div> 

                </div>
                 <div class="col-md-4 col-sm-4">
                      <div class="panel panel-default">

                    <div class="panel-body">
                         <h4 class="adjst">Tour Package Six #6 </h4>
                        <p>
                               Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                     Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.

                            </p>

                         <span class="label label-danger">Cost: 400 $</span>
                    </div>
                </div> 

                </div>
            </div>
        </div>
    </section>
    <!--END Package SECTION-->